name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  go-test:
    name: Go tests
    runs-on: [self-hosted, exe]
    steps:
      - uses: actions/checkout@v5
      - run: cd cmd/autoscaler && go test -short -v -count=1 -race ./...

  lint:
    name: Lint
    runs-on: [self-hosted, exe]
    steps:
      - uses: actions/checkout@v5
      - run: actionlint
      - run: shellcheck scripts/*.sh

  bats:
    name: Bats tests
    runs-on: [self-hosted, exe]
    steps:
      - uses: actions/checkout@v5
      - run: bats tests/
